### ISSUE TITLE
Problem with accessor descriptors

### ISSUE THREAD

**Issue by brettz9** [tmpvar/jsdom#1720]
I'm running into some strange behavior with `Object.defineProperty` used with an accessor descriptor in that when it is subsequently checked with `Object.getOwnPropertyDescriptor`, the `get` function originally supplied is no longer available (and `value` is there in its place).

```js
var jsdom = require("jsdom");

var window = jsdom.jsdom().defaultView;
Object.defineProperty(window, 'testVar', {enumerable: true, get: function () {
    return 'test';
}});
console.log('get' in Object.getOwnPropertyDescriptor(window, 'testVar')); // unexpectedly `false`
```

Available for testing on https://runkit.com/5864b94c65714b0014bfd65a/588fe1aee1800c0014f30c5d

And to confirm the fact that using the property nevertheless works fine in the same Node environment with `global` or an arbitrary object, see https://runkit.com/5864b94c65714b0014bfd65a/588fe2d39af44e00146a5322

Thanks!

**Comment by domenic** [comment]
This is likely related to regressions in Node.js v7.3.0 or 7.4.0 (I can't remember which). Try 7.2.1 and see if you still have the problem.

**Comment by brettz9** [comment]
It occurs in 6.9.2 and 7.4.0 and also in 7.2.1...

**Comment by domenic** [comment]
Ah right. I guess this is the older bug, https://github.com/nodejs/node/issues/2734

**Comment by brettz9** [comment]
Is this related?

```js
var jsdom = require("jsdom");
var window = jsdom.jsdom().defaultView;

Object.defineProperty(window, 'deleteable', {
    enumerable: false,
    writable: true,
    configurable: true,
    value: 'Deleteme'
});

delete window.deleteable; // Expect it would be deletable

console.log('window.deleteable === undefined', window.deleteable === undefined); // gives `false`
```

**Comment by domenic** [comment]
That is probably (but not definitely) https://github.com/nodejs/node/issues/6287, which looks like it might be fixed in the next Node.js release...

**Comment by domenic** [comment]
Closing as Node.js has been fixed.

**Comment by brettz9** [comment]
Using nvm, confirmed as Node version 7.9.0 (which is after the version at https://github.com/nodejs/node/pull/11185 which lists https://github.com/nodejs/node/issues/11266 which was referenced by https://github.com/nodejs/node/issues/6287 , the issue you mentioned it could be), I still see the same problem.

I guess I should report to Node then?

**Comment by domenic** [comment]
Oh, sorry, I got turned around, this is https://github.com/nodejs/node/issues/2734 which is still open...
